const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {personnelSetup,admin,user,other,epoch}=require('./personnel-db.cjs');
const root=path.resolve(__dirname,'..');
(async()=>{
 const {db,as,fn,eid,oid}=await personnelSetup();console.log('Browser DB initialized');let queue=Promise.resolve();const serial=op=>{const next=queue.then(op);queue=next.catch(()=>{});return next};
 const passwords=new Map([[eid,'employee-password-123'],[oid,'other-password-123']]),tokens=new Map([['admin-jwt',{uid:admin,epoch:null}]]);let documentCounter=0;
 const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+(req.url==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)||!fs.existsSync(file))return res.writeHead(404).end();res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});const errors=[];
 const sdk=`window.supabase={createClient:(u,k,o={})=>({auth:{getSession:async()=>({data:{session:JSON.parse(localStorage.getItem(o.auth?.storageKey||'hub-fixture')||'null')}}),setSession:async(s)=>{localStorage.setItem(o.auth.storageKey,JSON.stringify(s));return{};},signOut:async()=>{localStorage.removeItem(o.auth.storageKey);return{};}},storage:{from:()=>({uploadToSignedUrl:async()=>({error:null})})}})};`;
 async function prepare(page){page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'text/javascript',body:sdk}));await page.route('https://*.supabase.co/**',route=>serial(async()=>{
 const req=route.request(),name=new URL(req.url()).pathname.split('/').pop(),b=JSON.parse(req.postData()||'{}'),jwt=(req.headers().authorization||'').replace('Bearer ','');const token=tokens.get(jwt);
 const reply=(value,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value)});
 try{
 if(name==='token')return reply({user:{id:admin},access_token:'admin-jwt'});if(name==='overseers')return reply([{user_id:admin}]);if(name==='websites')return reply([]);if(name==='get_maintenance_mode')return reply(false);if(name==='get_enabled_managed_websites')return reply([]);if(name==='get_visible_announcements')return reply([{title:'Welcome',message:'New personnel network'}]);
 if(name==='personnel_selection')return reply(await fn('anon',null,name));
 if(name==='personnel_action')return reply(await as('authenticated',token?.uid,b.p_action,b.p_data,token?.epoch));
 if(name==='training_catalog')return reply(await fn(b.p_admin?'authenticated':'anon',b.p_admin?admin:null,name,[!!b.p_admin]));
 if(name==='personnel-auth'){
 if(b.action==='create'){
 if(token?.uid!==admin)throw Error('Admin required');const uid=crypto.randomUUID();await db.query('insert into auth.users values($1)',[uid]);const p=(await db.query('insert into public.personnel(user_id,callsign,title,permissions,join_date,auth_epoch)values($1,$2,$3,$4,$5,$6)returning id',[uid,b.callsign,b.title,b.permissions,b.join_date,epoch])).rows[0];passwords.set(p.id,b.password);return reply(p);
 }
 if(b.action==='login'){
 if(passwords.get(b.employee_id)!==b.password)return reply({error:'Invalid employee or password'},403);
 const p=(await db.query('select * from public.personnel where id=$1',[b.employee_id])).rows[0];if(p.status!=='active')throw Error('Login disabled');const access=crypto.randomUUID();tokens.set(access,{uid:p.user_id,epoch:p.auth_epoch});return reply({session:{access_token:access,refresh_token:'refresh',user:{id:p.user_id}}});
 }
 if(b.action==='reset-password'){const epoch2=await as('authenticated',admin,'admin-invalidate-auth',{employee_id:b.employee_id});passwords.set(b.employee_id,b.password);await as('authenticated',admin,'admin-complete-reset',{employee_id:b.employee_id,epoch:epoch2});return reply({message:'Password reset. Existing employee sessions are invalid.'});}
 if(b.action==='document-upload'){const d=await as('authenticated',admin,'admin-document-begin',{employee_id:b.employee_id,name:b.name,bytes:b.bytes,replaces:b.replaces});return reply({id:d.id,path:d.path,token:'upload'});}
 if(b.action==='document-finish'){await fn('service_role',null,'personnel_finish_document',[admin,b.id]);documentCounter++;return reply({message:'Uploaded'});}
 if(b.action==='document-view'){const d=await as('authenticated',token.uid,token.uid===admin?'admin-document-path':'document-path',{id:b.id},token.epoch);return reply({signedUrl:'https://pdf.test/'+d.id});}
 if(b.action==='temporary-create'){const code='a'.repeat(64);const info=await fn('service_role',null,'personnel_issue_temporary',[admin,crypto.createHash('sha256').update(code).digest('hex')]);return reply({...info,code});}
 if(b.action==='temporary-use'){if(!await fn('service_role',null,'personnel_claim_temporary',[crypto.createHash('sha256').update(b.code).digest('hex')]))throw Error('Used or invalid code');return reply({sites:[{name:'Example',url:'https://example.com'}],announcements:[]});}
 }
 return reply([]);
 }catch(e){return reply({message:e.message,error:e.message},403);}
 }));}
 const url=`http://127.0.0.1:${server.address().port}`;
 try{
 const a=await browser.newPage(),e=await browser.newPage();await prepare(a);await prepare(e);
 console.log('Browser navigating');await a.goto(url);await a.evaluate(()=>{window.overseerSession={access_token:'admin-jwt'};showOverseerPanel();});
 console.log('Browser categories');for(const name of ['PERSONNEL','REQUESTS','TRAINING ADMINISTRATION','WEBSITE ADMINISTRATION','ACCESS & SECURITY','MEDIA','SYSTEM'])assert(await a.getByRole('button',{name,exact:true}).isVisible());
 assert(!await a.getByRole('button',{name:'MANAGE RADIO MUSIC'}).isVisible());await a.getByRole('button',{name:'MEDIA',exact:true}).click();assert(await a.getByRole('button',{name:'MANAGE RADIO MUSIC'}).isVisible());await a.getByRole('button',{name:'BACK / RETURN TO OVERSEER TERMINAL'}).click();
 console.log('Browser employee create');await a.getByRole('button',{name:'PERSONNEL',exact:true}).click();await a.getByRole('button',{name:'+ ADD EMPLOYEE',exact:true}).click();await a.getByLabel('NAME / CALLSIGN').fill('New Person');await a.getByLabel('POSITION / TITLE').fill('Technician');await a.getByLabel('INITIAL PASSWORD').fill('initial-password-123');for(const permission of ['Use Personal Notes','Access Personal Documents','Submit Website Requests','Submit Training Requests','Create Training Drafts','Propose Training Set Edits'])await a.getByLabel(permission,{exact:true}).check();await a.getByRole('button',{name:'CREATE PERSONNEL RECORD'}).click();await a.getByRole('heading',{name:'New Person // PERSONNEL FILE'}).waitFor();
 const pid=(await db.query("select id from public.personnel where callsign='New Person'")).rows[0].id;
 console.log('Browser personal login');await e.goto(url);await e.evaluate(()=>showEmployeeLogin());await e.getByRole('button',{name:'New Person — Technician'}).click();await e.getByLabel('PERSONAL PASSWORD').fill('wrong-password-123');await e.getByRole('button',{name:'SIGN IN',exact:true}).click();await e.getByRole('status').getByText(/Invalid employee/).waitFor();
 await e.getByLabel('PERSONAL PASSWORD').fill('initial-password-123');await e.getByRole('button',{name:'SIGN IN',exact:true}).click();await e.getByRole('heading',{name:'WELCOME, New Person'}).waitFor();await e.reload();await e.getByRole('heading',{name:'WELCOME, New Person'}).waitFor();
 console.log('Browser notes');await e.getByRole('button',{name:'NOTES',exact:true}).click();await e.getByRole('button',{name:'+ NEW NOTE'}).click();await e.getByLabel('TITLE',{exact:true}).fill('<img src=x onerror="window.pwned=true">');await e.getByLabel('NOTE',{exact:true}).fill('My private note');await e.getByRole('button',{name:'SAVE',exact:true}).click();await e.getByRole('button',{name:'OPEN / EDIT'}).click();await e.getByLabel('NOTE',{exact:true}).fill('Edited note');await e.getByRole('button',{name:'SAVE',exact:true}).click();assert.equal(await e.locator('.personnel-card img').count(),0);assert.equal(await e.evaluate(()=>window.pwned),undefined);
 await a.getByLabel('OVERSEER PERSONNEL NOTE').fill('Private staff only');await a.getByRole('button',{name:'ADD PERSONNEL NOTE'}).click();await a.getByText(/Private staff only/).waitFor();await a.getByLabel('OVERSEER PERSONNEL NOTE').fill('Employee visible');await a.getByLabel('VISIBLE TO EMPLOYEE').check();await a.getByRole('button',{name:'ADD PERSONNEL NOTE'}).click();await a.getByText(/Employee visible/).waitFor();
 await e.getByRole('button',{name:'MY ROBCO',exact:true}).click();await e.getByRole('button',{name:'MY PERSONNEL FILE',exact:true}).click();assert.equal(await e.getByText(/Private staff only/).count(),0);await e.getByText(/Employee visible/).waitFor();
 await a.getByRole('button',{name:'PERSONNEL DOCUMENTS',exact:true}).click();await a.getByLabel('UPLOAD PDF').setInputFiles({name:'paper.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-test!')});await a.getByRole('button',{name:'UPLOAD DOCUMENT',exact:true}).click();await a.getByRole('heading',{name:'paper.pdf'}).waitFor();assert.equal(documentCounter,1);
 await e.getByRole('button',{name:'MY DOCUMENTS',exact:true}).click();await e.getByRole('heading',{name:'paper.pdf'}).waitFor();
 await e.getByRole('button',{name:'MY ROBCO',exact:true}).click();await e.getByRole('button',{name:'WEBSITE REQUESTS',exact:true}).click();await e.getByLabel('WEBSITE NAME').fill('Requested Example');await e.getByLabel('HTTPS / HTTP URL').fill('https://example.com');await e.getByLabel('DESCRIPTION',{exact:true}).fill('Good site');await e.getByRole('button',{name:'SUBMIT REQUEST',exact:true}).click();await e.getByRole('heading',{name:'Requested Example'}).waitFor();
 await a.getByRole('button',{name:'RETURN TO OVERSEER TERMINAL',exact:true}).click();await a.getByRole('button',{name:'REQUESTS',exact:true}).click();await a.getByRole('button',{name:'REVIEW WEBSITE REQUESTS'}).click();const c=a.locator('.personnel-card').filter({has:a.getByRole('heading',{name:'Requested Example'})});await c.getByLabel('OVERSEER RESPONSE').fill('Approved by Overseer');await c.getByRole('button',{name:'APPROVE & PUBLISH'}).click();await c.getByText('Approved by Overseer').waitFor();
 await e.getByRole('button',{name:'MY ROBCO',exact:true}).click();await e.getByRole('button',{name:'REQUEST HISTORY',exact:true}).click();await e.getByText(/Approved by Overseer/).waitFor();
 await e.getByRole('button',{name:'MY ROBCO',exact:true}).click();await e.getByRole('button',{name:'TRAINING REQUESTS',exact:true}).click();await e.getByRole('button',{name:'CREATE NEW STUDY SET PROPOSAL'}).click();await e.getByLabel('TITLE',{exact:true}).fill('Cells');await e.getByLabel('SUBJECT',{exact:true}).fill('Science');await e.getByLabel('UNIT',{exact:true}).fill('1');await e.getByLabel('BULK PASTE').fill('Cell | Basic unit');await e.getByRole('button',{name:'PREVIEW IMPORT'}).click();await e.getByRole('button',{name:'ADD PREVIEWED QUESTIONS'}).click();await e.getByRole('button',{name:'SAVE PRIVATE DRAFT'}).click();await e.getByRole('button',{name:'OPEN / EDIT DRAFT'}).click();await e.getByRole('button',{name:'SUBMIT FOR OVERSEER REVIEW'}).click();await e.getByRole('heading',{name:'TRAINING REQUESTS',exact:true}).waitFor();assert.equal((await db.query('select count(*)::int n from public.training_sets')).rows[0].n,0);
 await a.getByRole('button',{name:'RETURN TO OVERSEER TERMINAL',exact:true}).click();await a.getByRole('button',{name:'REQUESTS',exact:true}).click();await a.getByRole('button',{name:'TRAINING REQUESTS',exact:true}).click();await a.getByText('BEFORE — source at draft creation').click();await a.getByText('AFTER — proposed metadata and questions').click();await a.getByLabel('OVERSEER RESPONSE').fill('Published');await a.getByRole('button',{name:'APPROVED',exact:true}).click();await a.getByText('Published',{exact:true}).waitFor();assert.equal((await db.query('select count(*)::int n from public.training_sets')).rows[0].n,1);
 await e.getByRole('button',{name:'MY ROBCO',exact:true}).click();await e.getByRole('button',{name:'TRAINING REQUESTS',exact:true}).click();await e.getByRole('button',{name:'CREATE PRIVATE EDIT DRAFT'}).click();await e.getByRole('button',{name:'OPEN / EDIT DRAFT'}).click();await e.getByLabel('DESCRIPTION',{exact:true}).fill('Proposed edit');await e.getByRole('button',{name:'SUBMIT FOR OVERSEER REVIEW'}).click();await e.getByRole('heading',{name:'TRAINING REQUESTS',exact:true}).waitFor();assert.equal((await db.query('select description from public.training_sets')).rows[0].description,'');
 await a.getByRole('button',{name:'RETURN TO OVERSEER TERMINAL',exact:true}).click();await a.getByRole('button',{name:'ACCESS & SECURITY',exact:true}).click();await a.getByRole('button',{name:'TEMPORARY LIMITED ACCESS',exact:true}).click();await a.getByRole('button',{name:'GENERATE TEMPORARY ACCESS'}).click();await a.getByText(/EXPIRES IN: 04:/).waitFor();
 const temp=await browser.newPage();await prepare(temp);await temp.goto(url);await temp.evaluate(()=>showEmployeeLogin());await temp.getByRole('button',{name:'TEMPORARY LIMITED ACCESS'}).click();await temp.getByLabel('ONE-USE CODE').fill('a'.repeat(64));await temp.getByRole('button',{name:'REDEEM'}).click();await temp.getByRole('heading',{name:'READ-ONLY DIRECTORY SNAPSHOT'}).waitFor();assert.equal(await temp.getByRole('button',{name:'MY ROBCO'}).count(),0);await temp.close();
 await a.evaluate(()=>Personnel.directory());await a.getByRole('button',{name:'New Person — Technician // ACTIVE'}).click();await a.getByLabel('NEW PASSWORD').fill('reset-password-123');await a.getByRole('button',{name:'RESET PASSWORD',exact:true}).click();await a.getByRole('status').getByText(/Password reset/).waitFor();
 await e.getByRole('button',{name:'MY ROBCO',exact:true}).click();await e.getByRole('status').getByText(/Sign in to an active/).waitFor();
 await a.getByLabel('STATUS',{exact:true}).selectOption('archived');await a.getByRole('button',{name:'SAVE ROLE / PERMISSIONS / STATUS'}).click();await a.getByText('Technician // ARCHIVED',{exact:true}).waitFor();assert.equal((await as('authenticated',admin,'admin-profile',{employee_id:pid})).website_requests.length,1);
 await a.evaluate(()=>Personnel.directory());await a.getByLabel('FILTER',{exact:true}).selectOption('archived');await a.getByRole('button',{name:'SEARCH / REFRESH'}).click();await a.getByRole('button',{name:'New Person — Technician // ARCHIVED'}).waitFor();
 for(const width of [1280,390,320]){await a.setViewportSize({width,height:850});assert(await a.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await a.screenshot({path:path.join(root,'../personnel-mobile.png'),fullPage:true});await a.setViewportSize({width:1280,height:900});await a.screenshot({path:path.join(root,'../personnel-desktop.png'),fullPage:true});
 assert.deepEqual(errors,[]);console.log('personnel browser: admin categories/create/directory, personal login/wrong password/refresh, notes/XSS, note visibility, PDF upload, website request attribution/review/history, Training draft/import/edit/publication, temporary scope, reset invalidation, archive/history and desktop/mobile passed');
 }catch(error){console.error(error);throw error;}finally{await browser.close();await new Promise(r=>server.close(r));await db.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
